// <auto-generated />
using CryptoDepth.Domain.Data.Adapters;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoDepth.Domain.Migrations
{
    [DbContext(typeof(CryptoDepthDbContext))]
    [Migration("20240116163207_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoDepth.Domain.Dto.CoinGekoPars+TopCoinsInfo", b =>
                {
                    b.Property<int>("Uq_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Uq_Id"));

                    b.Property<decimal>("CostToMoveDownUsd1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CostToMoveDownUsd2")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CostToMoveDownUsd3")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CostToMoveUpUsd1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CostToMoveUpUsd2")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CostToMoveUpUsd3")
                        .HasColumnType("numeric");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Name1")
                        .HasColumnType("text");

                    b.Property<string>("Name2")
                        .HasColumnType("text");

                    b.Property<string>("Name3")
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.HasKey("Uq_Id");

                    b.ToTable("TopCoinsInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
